package com.yuliakazachok.synloans.desktop.core

object TextResources {

    const val error = "Произошла ошибка"
    const val cancel = "Отмена"
    const val backMain = "Вернуться на главную"
    const val divider = " / "
    const val percent = " %"

    const val signIn = "Войти"
    const val signUp = "Зарегистрироваться"
    const val authorization = "Авторизация"
    const val registration = "Регистрация"

    const val email = "Электронная почта"
    const val password = "Пароль"
    const val passwordAgain = "Повторите пароль"
    const val fullName = "Полное наименование"
    const val shortName = "Сокращенное наименование"
    const val inn = "ИНН"
    const val kpp = "КПП"
    const val legalAddress = "Юридический адрес"
    const val actualAddress = "Фактический адрес"
    const val creditOrganisation = "Кредитная организация"

    const val profile = "Профиль"
    const val editProfile = "Редактирование профиля"
    const val save = "Сохранить"

    const val requests = "Заявки"
    const val ownRequests = "Мои заявки"
    const val otherRequests = "Открытые заявки"
    const val dateCreate = "Дата создания "
    const val dateIssue = "Дата выдачи "
    const val emptyCurrentRequests = "Нет текущих заявок!"
    const val emptyActiveRequests = "Нет активных заявок!"
    const val infoRequest = "Информация о заявке"
    const val approveBankAgent = "Согласие на роль банка-агента"
    const val status = "Статус"
    const val statusOpen = "Открыта"
    const val statusTransfer = "Банки отправляют переводы"
    const val statusIssue = "Кредит выдан"
    const val statusClose = "Закрыта"
    const val sum = "Сумма"
    const val sumThousand = "Сумма, тыс"
    const val maxRate = "Максимальный процент"
    const val term = "Срок"
    const val paymentSchedule = "График платежей"
    const val join = "Присоединиться"
    const val joinSyndicate = "Вступить в синдикат"
    const val cancelRequest = "Отменить заявку"
    const val banks = "Банки-участники"
    const val borrower = "Заемщик"

    const val billionSum = " млрд руб"
    const val millionSum = " млн руб"
    const val thousandSum = " тыс руб"

    const val monthsOne = " месяц"
    const val monthsFew = " месяца"
    const val monthsMany = " месяцев"
}