package com.yuliakazachok.synloans.desktop.core

object TextResources {

    const val error = "Произошла ошибка"
    const val repeat = "Повторить"
    const val cancel = "Отмена"
    const val backMain = "Вернуться на главную"
    const val backRequest = "Вернуться к заявке"
    const val divider = " / "
    const val percent = " %"

    const val signIn = "Войти"
    const val signUp = "Зарегистрироваться"
    const val authorization = "Авторизация"
    const val registration = "Регистрация"

    const val email = "Электронная почта"
    const val password = "Пароль"
    const val passwordAgain = "Повторите пароль"
    const val fullName = "Полное наименование"
    const val shortName = "Сокращенное наименование"
    const val inn = "ИНН"
    const val kpp = "КПП"
    const val legalAddress = "Юридический адрес"
    const val actualAddress = "Фактический адрес"
    const val creditOrganisation = "Кредитная организация"

    const val profile = "Профиль"
    const val editProfile = "Редактирование профиля"
    const val save = "Сохранить"

    const val requests = "Заявки"
    const val ownRequests = "Принятые заявки"
    const val otherRequests = "Другие заявки"
    const val dateCreate = "Дата создания "
    const val dateIssue = "Дата выдачи "
    const val emptyRequests = "Нет заявок"
    const val infoRequest = "Информация о заявке"
    const val approveBankAgent = "Согласие на роль банка-агента"
    const val status = "Статус"
    const val statusOpen = "Открыта"
    const val statusReadyToIssue = "Готов к выдаче"
    const val statusTransfer = "Банки отправляют переводы"
    const val statusIssue = "Выдан"
    const val statusClose = "Закрыта"
    const val sum = "Сумма"
    const val maxRate = "Максимальный процент"
    const val term = "Срок"
    const val join = "Присоединиться"
    const val joinSyndicate = "Вступить в синдикат"
    const val cancelRequest = "Отменить заявку"
    const val banks = "Банки-участники"
    const val borrower = "Заемщик"
    const val creationRequest = "Создание заявки"
    const val createRequest = "Создать заявку"
    const val sendRequest = "Отправить заявку"
    const val infoBank = "Информация о банке"
    const val paymentSchedule = "График платежей"
    const val payments = "Платежи"
    const val datePayment = "Дата платежа: "
    const val sumPayment = "Сумма платежа: "
    const val principal = "Основной: "
    const val percents = "Проценты: "
    const val notBanks = "Нет участников синдиката"
    const val exitSyndicate = "Выйти из синдиката"
    const val startCredit = "Получить кредит"
    const val notPayments = "Нет платежей"
    const val makePayment = "Внести платеж"
    const val send = "Отправить"

    const val billionSum = " млрд руб"
    const val millionSum = " млн руб"
    const val thousandSum = " тыс руб"
    const val unitSum = " руб"

    const val monthsOne = " месяц"
    const val monthsFew = " месяца"
    const val monthsMany = " месяцев"
}